### ISSUE TITLE
Getting false on isSupported function

### ISSUE THREAD

**Issue by manoj2166** [robinpowered/react-native-mdm#20]
Hi, 
I am getting false value after configure all the thing in android
Do the changes in AndroidMenifest.xml

<meta-data android:name="android.content.APP_RESTRICTIONS"
            android:resource="@xml/app_restrictions" />

Added app_restrictions.xml
<?xml version="1.0" encoding="utf-8"?>
<restrictions xmlns:android="http://schemas.android.com/apk/res/android">

    <restriction
        android:key="downloadOnCellular"
        android:title="@string/download_on_cell_title"
        android:restrictionType="bool"
        android:description="@string/download_on_cell_description"
        android:defaultValue="true" />

</restrictions>

Can anybody help me using version 1.0.5

**Comment by manoj2166** [comment]
Hi,
**getManifestRestrictions()** is working in the place of **getApplicationRestrictions()** 
Could you please let me know what is the issue?

**Comment by manoj2166** [comment]
Working going to close it.

**Comment by karthikkmca** [comment]
MobileDeviceManager.isSupported() false response
![image](https://user-images.githubusercontent.com/94790948/204858113-3d6f9ae1-c9af-4571-96ce-dc2e8b751a94.png)

**Comment by superyarik** [comment]
@manoj2166 how you solve it?
